import{a as g,S as L,i as c}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const b="https://pixabay.com/api/",S="54179353-52b74677f97422d49d8297fd1";async function w(t,o){return(await g.get(b,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const f=document.querySelector(".gallery");document.querySelector(".loader");const m=document.querySelector(".load-more"),q=new L(".gallery a",{captionsData:"alt",captionDelay:250});function v(t){const o=t.map(({webformatURL:a,largeImageURL:i,tags:e,likes:r,views:s,comments:h,downloads:p})=>`
    <li class=gallery-item>
    <a href="${i}">
        <img src="${a}" alt="${e}" />
    </a>
    <div class=gallery-info>
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${h}</p>
        <p><b>Downloads:</b> ${p}</p>
    </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),q.refresh()}function P(){f.innerHTML=""}function M(){document.querySelector(".loader").classList.remove("is-hidden")}function B(){document.querySelector(".loader").classList.add("is-hidden")}function E(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}const $=document.querySelector(".form");let l="",n=1;const u=15;$.addEventListener("submit",O);document.querySelector(".load-more").addEventListener("click",x);async function O(t){t.preventDefault(),l=t.currentTarget.elements["search-text"].value.trim(),l&&(n=1,P(),d(),await y())}async function x(){n+=1,d(),await y()}async function y(){try{M();const t=await w(l,n,u);if(t.hits.length===0&&n===1){c.error({message:"Sorry, there are no images matching your search query. Please try again."});return}v(t.hits);const o=Math.ceil(t.totalHits/u);n>=o?(c.info({message:"We're sorry, but you've reached the end of search results."}),d()):E(),n>1&&A()}catch{c.error({message:"Something went wrong."})}finally{B()}}function A(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
