import{a as h,S as g,i as c}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const b="https://pixabay.com/api/",L="54179353-52b74677f97422d49d8297fd1";async function S(t,o){return(await h.get(b,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const f=document.querySelector(".gallery"),w=new g(".gallery a",{captionsData:"alt",captionDelay:250});function v(t){const o=t.map(({webformatURL:i,largeImageURL:a,tags:e,likes:r,views:n,comments:y,downloads:p})=>`
    <li class=gallery-item>
    <a href="${a}">
        <img src="${i}" alt="${e}" />
    </a>
    <div class=gallery-info>
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${y}</p>
        <p><b>Downloads:</b> ${p}</p>
    </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),w.refresh()}function q(){f.innerHTML=""}function P(){document.querySelector(".loader").classList.remove("is-hidden")}function E(){document.querySelector(".loader").classList.add("is-hidden")}const $=document.querySelector(".form"),l=document.querySelector(".load-more");let d="",s=1;const u=15;$.addEventListener("submit",M);l.addEventListener("click",O);async function M(t){t.preventDefault(),d=t.currentTarget.elements["search-text"].value.trim(),d&&(s=1,q(),await m())}async function O(){s+=1,await m()}async function m(){try{P();const t=await S(d,s,u);if(t.hits.length===0&&s===1){c.error({message:"Sorry, there are no images matching your search query. Please try again."});return}v(t.hits);const o=Math.ceil(t.totalHits/u);s>=o?(l.classList.add("is-hidden"),c.info({message:"We're sorry, but you've reached the end of search results."})):l.classList.remove("is-hidden"),s>1&&x()}catch{c.error({message:"Something went wrong."})}finally{E()}}function x(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
